kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ ((.Values.rolebinding).name_projadmin) }}
  namespace: {{ ((.Values.namespace).name) }}
subjects:
- kind: Group
  name: {{ ((.Values.rolebinding).group_projadmin) }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io