{{- if or (not .Values.quotas.enabled) .Values.quotas.enabled }}
{{- if and .Values.quotas.pods .Values.quotas.cpuRequest .Values.quotas.memoryRequest .Values.quotas.cpuLimit .Values.quotas.memoryLimit }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace.name }}-quota
  namespace: {{ .Values.namespace.name }}
spec:
  hard:
    pods: {{ .Values.quotas.pods }}
    requests.cpu: {{ .Values.quotas.cpuRequest }}
    requests.memory: {{ .Values.quotas.memoryRequest }}
    limits.cpu: {{ .Values.quotas.cpuLimit }}
    limits.memory: {{ .Values.quotas.memoryLimit }}
{{- end }}
{{- end }}
