kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rolebinding.name-viewer }}
  namespace: {{ .Values.namespace.name }}
subjects:
- kind: Group
  name: {{ .Values.rolebinding.group-viewer }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io