{{- if .Values.limitRange }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace.name }}-pod-limits
  namespace: {{ .Values.namespace.name }}
spec:
  limits:
  - type: Pod
    min:
      cpu: {{ .Values.limitRange.pod.min.cpu }}
      memory: {{ .Values.limitRange.pod.min.memory }}
    max:
      cpu: {{ .Values.limitRange.pod.max.cpu }}
      memory: {{ .Values.limitRange.pod.max.memory }}
  - type: Container
    defaultRequest:
      cpu: {{ .Values.limitRange.container.defaultRequest.cpu }}
      memory: {{ .Values.limitRange.container.defaultRequest.memory }}
    default:
      cpu: {{ .Values.limitRange.container.default.cpu }}
      memory: {{ .Values.limitRange.container.default.memory }}
{{- end }}
