{{- if .Values.limitRange }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace.name }}-pod-limits
  namespace: {{ .Values.namespace.name }}
spec:
  limits:
  - type: Pod
    min:
      cpu: {{ .Values.limitRange.pod.min.cpu | quote }}
      memory: {{ .Values.limitRange.pod.min.memory | quote }}
    max:
      cpu: {{ .Values.limitRange.pod.max.cpu | quote }}
      memory: {{ .Values.limitRange.pod.max.memory | quote }}
{{- end }}
