apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.projectName }}-quota
  namespace: {{ .Values.projectName }}
spec:
  hard:
    pods: {{ .Values.quotas.pods }}
    requests.cpu: {{ .Values.quotas.cpuRequest }}
    requests.memory: {{ .Values.quotas.memoryRequest }}
    limits.cpu: {{ .Values.quotas.cpuLimit }}
    limits.memory: {{ .Values.quotas.memoryLimit }}
