kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceaccount.name }}-edit-rolebinding
  namespace: {{ .Values.namespace.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount.name }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
