apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-config
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/turbra/gitops-project-ob.git
      revision: main
      files:
        - path: environment/*/*-*/values.yaml
  template:
    metadata:
      # The application name in ArgoCD is derived from the directory structure.
      # Given the format environment/{env}/{appName}-{env}/values.yaml, it picks the {appName}-{env} segment.
      name: '{{path[2]}}'
    spec:
      project: project-config
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: 'https://github.com/turbra/gitops-project-ob.git'
        targetRevision: main
        path: 'environment/{{path[1]}}/helm'
        helm:
          valueFiles:
          - '../{{path[2]}}/values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: openshift-gitops

