apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-config
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/turbra/gitops-project-ob.git
      revision: test
      directories:
      - path: environment/dev/
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: project-config
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: 'https://github.com/turbra/gitops-project-ob.git'
        targetRevision: test
        path: environment/dev/helm
        helm:
          valueFiles:
          - '../environment/dev/*'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: openshift-gitops
