apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-config
  namespace: openshift-gitops
spec:
  description: 'Project onboarding'
  sourceRepos:
    - 'https://github.com/turbra/gitops-project-ob.git'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
